services:
 
  app:
    build: .
    container_name: projeto-Sentinela
    ports:
      - "3010:3002"
    volumes:
      - dados_sentinela:/app/backend/data
 
volumes:
 
  dados_painel:


